# Generated by Django 5.1.1 on 2025-02-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblBenchmark',
            fields=[
                ('bnc_id', models.AutoField(primary_key=True, serialize=False)),
                ('bnc_process', models.CharField(max_length=255, unique=True)),
                ('bnc_normal', models.IntegerField(blank=True, null=True)),
                ('bnc_warning', models.IntegerField(blank=True, null=True)),
                ('bnc_critical', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_benchmark',
            },
        ),
        migrations.CreateModel(
            name='TblEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField()),
                ('site_id', models.IntegerField()),
                ('system_id', models.IntegerField()),
                ('bnc_id', models.IntegerField()),
                ('event_value', models.IntegerField()),
                ('event_type', models.CharField(max_length=15)),
                ('event_email', models.TextField()),
                ('event_emaildelivery', models.IntegerField()),
                ('event_creation_date', models.DateTimeField(blank=True, null=True)),
                ('tmp_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_event',
            },
        ),
        migrations.CreateModel(
            name='TblEventTmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('site', models.CharField(max_length=255)),
                ('system', models.CharField(max_length=255)),
                ('bench', models.CharField(max_length=255)),
                ('event_value', models.IntegerField()),
                ('event_email', models.TextField()),
                ('event_emaildelivery', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_event_tmp',
            },
        ),
        migrations.CreateModel(
            name='TblStatus',
            fields=[
                ('status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tbl_status',
            },
        ),
        migrations.CreateModel(
            name='TblTmpclear',
            fields=[
                ('tmp_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tbl_tmpclear',
            },
        ),
        migrations.CreateModel(
            name='TblClients',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.CharField(max_length=200)),
                ('client_contact', models.CharField(max_length=30)),
                ('client_address', models.TextField()),
                ('client_creation_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_clients',
                'unique_together': {('client_name', 'client_email')},
            },
        ),
        migrations.CreateModel(
            name='TblSites',
            fields=[
                ('site_id', models.AutoField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=255)),
                ('site_email', models.CharField(max_length=200)),
                ('site_contact', models.CharField(max_length=30)),
                ('site_address', models.TextField()),
                ('site_status', models.IntegerField()),
                ('client_id', models.IntegerField()),
                ('site_creation_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_sites',
                'unique_together': {('site_name', 'site_email', 'client_id')},
            },
        ),
        migrations.CreateModel(
            name='TblSystem',
            fields=[
                ('system_id', models.AutoField(primary_key=True, serialize=False)),
                ('system_name', models.CharField(max_length=200)),
                ('system_ip', models.CharField(max_length=30)),
                ('system_use', models.TextField()),
                ('system_status', models.IntegerField()),
                ('site_id', models.IntegerField()),
                ('system_creation_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_system',
                'unique_together': {('system_name', 'system_ip', 'site_id')},
            },
        ),
    ]
